AWSTemplateFormatVersion: '2010-09-09'
Resources:
 WebsiteBucket:
  Type: AWS::S3::Bucket
  Properties:
   BucketName: awstestgastonisnardi
   AccessControl: PublicRead
   WebsiteConfiguration:
    IndexDocument: index.html
    ErrorDocument: index.html
